### ISSUE TITLE
Command "flint" throws "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by shuson** [flintjs/flint#100]
OS: Window 7 64bit
node: 0.12.0
npm: 2.5.1

How to reproduce:
1, npm install -g flint. This goes fine without error.
2, type flint in a directory.

Then it throws error:

```
var uid = process.getuid();
                  ^
TypeError: undefined is not a function
```
The file  is ...\AppData\Roaming\npm\node_modules\flint\node_modules\flint-runner\lib\compat\lib\exec.js:6

Updates:

Refer to: https://nodejs.org/api/process.html#process_process_getuid
```process.getuid()``` is only available on  POSIX platforms.

**Comment by natew** [comment]
I touched that file today. I'll check into it. Oh I see you're on Windows. We don't have it on Windows yet. We are trying to get it stable on Mac. I will post here when we have some news on that.

**Comment by shuson** [comment]
Thanks Nate, I turn to my mac later
