### ISSUE TITLE
Better compile-time checks for whether to wrap

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#108]
Right now our logic says "is the variable we're currently setting in our current scope"

when the better question is "is the variable we're setting at the top level of the view"

```js
view Name {
  let first = 'haskell'
  let last = 'curry'
  
  let go = () => {
    let inner = 4
    let really = () => {
      inner = 5  // 
      first = 'john'
    }
    setTimeout(really)
  }
  
  <h1>name is {first} {last}</h1>
  <input sync={first} />
  <input sync={last} />
  <button onClick={go}>go</button>
}
```

currently both "first" and "inner" are wrapped with view.set in the really() function. Only first should actually be wrapped though, because inner is part of the pure go function

**Comment by natew** [comment]
Fixed in https://github.com/flintjs/flint/commit/4691df11ada597af2beeab4d431b424358d9272c
