### ISSUE TITLE
observe

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#117]
This is meant to be primarily a discussion / idea thread with community for a bit before we talk about implementing it

we could implement observe fairly easily at the compiler level (as long as we kept the first parameter simple, but we could throw error if not)

I wanted to do something like this
```js
observe(isAltKeyDown, val => { val ? showInspector() : hideInspector() })
```
but instead I had to do it procedurally, which isn't as nice.

**Comment by natew** [comment]
Closing, we should probably leave this off until we are really stable, dont want it distracting people.
