### ISSUE TITLE
Smarter hot updates

### ISSUE THREAD

**Issue by natew** [flintjs/flint#12]
We'd need to hook into babel and:

- [x] Use babel to do all view transformation
- [x] Alternatively, we could hack around this by just having babel read something to detect views
- [x] Once inside views, wrap all getters that are one level inside view:

```js
// before
view Main { let name = 'one' }
// after
view Main { let name = view.get('name', 'one') }
```

Why? This would enable super smart hot updating, which gives us:

- [x] Components keep their state on save even when other parts of them change
- [x] Components update only the state that is changed (keep state of non-changed variables)
- [x] If you change a variable inside the file, views can keep state
- [x] Sub-views keep state even when parent changes (just check if props change)

**Comment by natew** [comment]
With the flint-transform babel plugin we now wrap all getters like specified here, ready for stage 2.

**Comment by natew** [comment]
Boom! Implemented most everything except for only updating the actually changed state. That will require a bit more work...

**Comment by ncammarata** [comment]
:boom:

**Comment by natew** [comment]
🎂🎉
