### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#138]
Can't give a ton of hints why, but I got this after running an app for a long time
![image](https://cloud.githubusercontent.com/assets/204989/11113945/9dd51ae6-88d5-11e5-861f-292fd07003ac.png)

**Comment by natew** [comment]
Closing not because it's resolved but because it's really scary to see this here and I did a lot of profiling this morning with no leaks detected. We can keep an eye out for it going forward.
