### ISSUE TITLE
% in URL crashes Flint dev server

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#140]
![image](https://cloud.githubusercontent.com/assets/699733/11130090/fdbebf18-8937-11e5-8f30-644ec2403a76.png)

**Comment by natew** [comment]
Seems like its a bad url: https://github.com/strongloop/express/issues/2652

Ok to close? If there was an easier loose config I could throw it in but I couldn't see any query-parser that would be pluggable easily.

**Comment by liron00** [comment]
Ya no biggie
