### ISSUE TITLE
Bind an event handler to when a (state) variable value changes

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#142]
A common pattern is that I have something like a month picker, a day picker and a year picker, which each have the effect of mutating a `birthday` state variable. I would then like to run some code, e.g. to call `view.props.onBirthdayChange({birthday})`, whenever `birthday` changes.

**Comment by natew** [comment]
Yea, this ties in with https://github.com/flintjs/flint/issues/117

Without a decent system for observing and reacting to variables, it sort of forces you into these ugly models where you bundle together a bunch of changes, and it's not very granular as it should be.

Then you could write:

```js
view Something {
  observe(birthday, view.props.onBirthday)
}```

**Comment by natew** [comment]
Closing, we're having a general discussion on this but it's outside of "issue" scope I think
