### ISSUE TITLE
Weird syntax-parsing bug when a function param is called "tag"

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#144]
![image](https://cloud.githubusercontent.com/assets/699733/11166710/ae333c1a-8af6-11e5-870e-62833c99a682.png)
![image](https://cloud.githubusercontent.com/assets/699733/11166715/b63830dc-8af6-11e5-846c-8b93f3d4bb9d.png)

What's weird is that if I just change "tag" to "ta" or "tagx", everything is fine.

**Comment by natew** [comment]
Yea I messed up Babel I was playing with tag as a reserved word. I tried to remove it but I don't see where it is haha will revisit this.

**Comment by natew** [comment]
Fixed https://github.com/flintjs/babel/commit/72aa4568f5aca3b1dff8468e3f8546100faa1462
