### ISSUE TITLE
hot inject index.html errors

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#145]

**Comment by natew** [comment]
What does this mean?

**Comment by ncammarata** [comment]
sorry, filed this quickly while with user. They were changing index.html and it was live injecting into the site as a script tag. In the best case the runner should honor the path and refresh the browser, but the easy solution now is just do nothing and wait for a hard-refresh. Right now it just errors.

**Comment by natew** [comment]
Should be fixed by out of bounds file path checks in live coding https://github.com/flintjs/flint/commit/3ef424f990bd8fe57b12fc387c1b869c3dc2f420
