### ISSUE TITLE
Remove tap delay

### ISSUE THREAD

**Issue by natew** [flintjs/flint#147]

**Comment by ncammarata** [comment]
for these types of opinionated runtime changes (while I'm for them) they should be super easy to undo/remove and probably implemented as a type of plugin #72

**Comment by natew** [comment]
Yea meant this specifically for our site just added to wrong spot, my bad.

**Comment by natew** [comment]
Added in https://github.com/flintjs/site/commit/b95b87926471900913c7738900f985f2949b6611
