### ISSUE TITLE
Problem styling non-Flint components using $ComponentName

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#149]
Styling an external component like this:

    import Imgix from 'react-imgix'
    view Foo {
        <Imgix />

        $Imgix = {
            width: 100,
            height: 100
        }
    }

Since the `Imgix` isn't a Flint-generated component, it renders as an `<img>` tag without getting wrapped in an `<imgix>` tag. Then the `$Imgix` style fails to select that `<img>` tag.

A workaround is to simply set a class and select on the class.

**Comment by natew** [comment]
I think we changed this recently because we had run into a few small things. We should fall back to just passing the style as an object.

**Comment by natew** [comment]
Oh so it is passing style just not being handled by imgix? That would probably be something they would have to solve on the library end. Checking out...

**Comment by natew** [comment]
Closing, this should pass just style prop which is the best we can do for now
