### ISSUE TITLE
Install indicator for bluebird when used await

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#16]

**Comment by ncammarata** [comment]
don't actually have a test case for this yet, but it happened in my running app and I wanted to jot it down

**Comment by natew** [comment]
Was about to fix this but have a thought: as a developer I may try and use async/await just experiment and I'd see that install indicator come in. It would be nice to see it, would let me know:

1. Bluebird powers our async/await
2. It works in the first place.

Plus it only happens once time.
