### ISSUE TITLE
Example ideas

### ISSUE THREAD

**Issue by natew** [flintjs/flint#162]
One came up today that is good is showing import/export between files.

**Comment by ncammarata** [comment]
[ ] importing components. Ideally showing using an angular, react, and jQuery components. Really need to push the "flint doesnt prohibit you from using other things" 
[ ] canvas
[ ] animation
[ ] Data - redux/flux/firebase
[ ] todomvc
[ ] mini-spotify clone (shows using <audio>)
[ ] airbnb clone (shows filtering through data, a modal, repeat)
