### ISSUE TITLE
The $class matching doesn't seem to work when using the element syntax to pass view.props.children

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#168]
view Foo {
        <Bar>
            <baz class="c" />
        </Bar>

        $c = {
            // won't work
        }
    }

    view Bar {
       {view.props.children}
    }

**Comment by natew** [comment]
May have broken recently, but we have the logic there (added it in the last week or so). Will check it out.

**Comment by natew** [comment]
Good catch, fixed https://github.com/flintjs/flint/commit/163fccff43b8ad02361409f4fb11d8881a02b009
