### ISSUE TITLE
Know Live Coding state in flint.js, use for console

### ISSUE THREAD

**Issue by natew** [flintjs/flint#169]
To better debounce things, we should have the state of live coding in flint.js and shim console/log/error/warn.

**Comment by ncammarata** [comment]
Also know if the current atom editor is open so we can show/hide edit in context menus, in inspector

**Comment by natew** [comment]
https://github.com/flintjs/flint/commit/7ff67bd2d1e083400a8bd09f6701ec1cd012561c
