### ISSUE TITLE
Remove React-ID

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#17]
The dom is currently the hardest part about developing with Flint on a real application

![image](https://cloud.githubusercontent.com/assets/204989/10601009/62d832e4-76c3-11e5-9d46-6a209df2657e.png)

**Comment by gaearon** [comment]
AFAIK React is going to drop hierarchical IDs in master soon.

**Comment by natew** [comment]
facebook/react#1570

**Comment by natew** [comment]
Closing as it's not under direct control.
