### ISSUE TITLE
Double style error

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#18]
```js
view Main {
  $h1 = { color: 'red' }
  $h1 = { color: 'red' }
}
```

Should throw a compile-time error saying "you've defined $h1 twice". We've both run into this many times and it would be a huge usability win

**Comment by natew** [comment]
Actually not as simple as I thought. Babel doesn't seem to recognize it easily. We'd probably have to do runtime, with some sort of object.freeze system.

**Comment by natew** [comment]
Tried again. This opens up some good problems with our weird style syntax. It comes through technically as a global variable reassignment in Babel.

```
$name = {}
```

Looks like you're trying to redefine a global variable `$name`. It's really odd. And beyond that and the props, it's the only things left that are controversial. We should think about this.

**Comment by natew** [comment]
Fixed https://github.com/flintjs/flint/commit/5815bf6b84577c72df93f3279eeb2a6f221444bc
