### ISSUE TITLE
Routing 404

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#19]
Not even sure if this makes sense, but I need it for an app and there wasn't an obvious way to do it. Would be a use of compile-time routing

**Comment by natew** [comment]
Yea this is open, given we just added routes. Nothing too elegant actually off the top of my head comes up, it doesn't fit too well with the route param in any way. Maybe `<View route={{ status: 404, route: '/path' }} />`

**Comment by natew** [comment]
`<NotFound route="404" />` ?

**Comment by ncammarata** [comment]
would 404 be special? Baked into our router? That might not be clear if it's just a string like their own routes

**Comment by natew** [comment]
Actually we could do `route={404}` that way you definitely know integer == status code. May implement this one.

**Comment by natew** [comment]
https://flintjs.com/404
