### ISSUE TITLE
`flint new` hangs on fresh install

### ISSUE THREAD

**Issue by seldo** [flintjs/flint#2]
Trying out flint on node 4.1.2 with npm 3.3.5 the installer hangs when I run `flint new appname3`. I tried `-ddd` and the only output I got was

```
Looking for updated scaffold in https://github.com/flint-lang/scaffold
Creating app...
```

Is this a known issue?

**Comment by natew** [comment]
Hey, for some reason didn't get notification on this, apologies.

Flint is pre-beta actually, but as of the last few days should be working better.

If you run `flint new appname --debug` we may be able to get better output, I just pushed a version that should log that better.

**Comment by seldo** [comment]
Here's your debug output: https://gist.github.com/seldo/fe1ec302b95d408711fb

If I'm reading it correctly, it seems the working directory of the CLI is that of the module, not that of the directory it creates, and thus the scaffold creation is failing due to perms issues.

**Comment by ncammarata** [comment]
@seldo thanks for the output. Permissions issues should be all fixed now.

Do npm uninstall flint -g and try again with the curl script. If it doesn't work for some reason if it doesn't work please feel free to ping me personally(slack) and I'll help you out. Either way feel free to hang out!
(our slack - https://flint-slack.herokuapp.com/)

**Comment by natew** [comment]
@seldo Pushed just now another change that uses your `~/.flint` directory for caching scaffolds (which allows for offline use). Give it a whirl.
