### ISSUE TITLE
Properly doing async/await in Flint

### ISSUE THREAD

**Issue by mglukhovsky** [flintjs/flint#205]
I'm still getting up to speed with ES6 syntax and `async`/`await`, so I may be doing something incorrectly. I have a working example that uses an `async` function from an external file (taken from the `fetch` example), as follows:
 
`main.js`:
```
import { data, update } from './helpers'

view Main {
    load()
    async function load() {
        output = await update()
        console.log('Updated:', data)
        view.update()
    }
    ....
}
```

`helpers.js`:
```
let data = []
async function update() {
    gotData = await fetch.json('http://some-json-api.com/')
    data.push(...gotData)
}
export default {updateRepo}
```

---

However, this seems overly complicated. 

I would expect to be able to follow this pattern instead in `main.js`:

`main.js`:
```
import { data, update } from './helpers'

view Main {
    (async () => {
        await update() 
        console.log('Updated:', data)
        view.update()
    })()
}
```

...but Flint reports an error:

```
/main.js: Unexpected token (8:20)
line: 8, col: 20

 SyntaxError: /Users/michael/flint/www-preview/main.js: Unexpected token (8:20)
   6 |
   7 |   (async () => {
>  8 |     await update()
     |                     ^
   9 |     console.log('Update:',data)
  10 |     view.update()
```

Any ideas on why this syntax error appears?

**Comment by ncammarata** [comment]
@natew can answer this better than I can, but I've confirmed that it works in the version of Babel we're using, so it is likely a Flint specific issue

**Comment by natew** [comment]
Yea async/await is a *little* sketchy in babel, we are also on 5.8 (6 is bringing improvements but for now its actually a downgrade, waiting on a few tickets).

The example you pasted is super complex. I've been doing something closer to this:

https://github.com/natew/arena/blob/7bfb364287c7b0ecc5654d8cb7dbe2ceb2144b1e/project.js#L9

**Comment by mglukhovsky** [comment]
@natew: thanks for the link! Your example helps detail some useful patterns for Flint.

**Comment by ncammarata** [comment]
https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=%20%20(async%20function()%20%7B%0A%20%20%20%20await%20update()%0A%20%20%20%20console.log('Updated%3A'%2C%20data)%0A%20%20%20%20view.update()%0A%20%20%7D)()%0A

seems to work though

**Comment by natew** [comment]
Cleaning up stuff, going to close. Going to start a "documentation" ticket and add a few things we need to cover
