### ISSUE TITLE
charAt error in tools on beta.12 hello world

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#209]
![image](https://cloud.githubusercontent.com/assets/204989/11989073/827e0af8-a9c5-11e5-9a03-ebffcf63262b.png)

![image](https://cloud.githubusercontent.com/assets/204989/11989079/9db5c19e-a9c5-11e5-9968-d104ad2c22a9.png)

in requireFactory.js

**Comment by natew** [comment]
This means you've not rebuilt tools properly yet and it's running an old version.
