### ISSUE TITLE
Fresh run of Flint on beta .12 errors and fails

### ISSUE THREAD

**Issue by nobidin** [flintjs/flint#210]
![image](https://cloud.githubusercontent.com/assets/5089994/11997557/c9e38134-aa4c-11e5-9d96-04efa2285853.png)

```
module.js:328
    throw err;
    ^
Error: Cannot find module '/usr/local/lib/node_modules/flint/node_modules/flint-runner/node_modules/flint-runner/dist/serverProcess'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by natew** [comment]
Can you get me node/npm version?

Just did a fresh install on my machine and its passing, also our CircleCI build is passing so probably something environmental.

**Comment by natew** [comment]
(oh i see node version). Hm... can you show me:

```
ls -la $(npm root -g) | grep flint
```

**Comment by natew** [comment]
This should be fixed in https://github.com/flintjs/flint/commit/650773fab306433c0c5b65e097eb94886e012aca
