### ISSUE TITLE
`flint build` truncates folder of .jpg's to first 25

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#214]
I have a folder called /static/images with 30 .jpg files in it. When I do `flint build`, the folder .flint/build only contains the first 25 .jpg files alphabetically.

**Comment by natew** [comment]
Upgraded our build system copy operations in https://github.com/flintjs/flint/commit/41351c02eb2ca2e8068f083bab81083e84eb1fed

Tested on an example app and have consistent copies, give it a spin!
