### ISSUE TITLE
Allowing an ES6 call in the compiled code

### ISSUE THREAD

**Issue by GuyHadas** [flintjs/flint#218]
www.mrRight.net is not working on my mobile phone (either safari or chrome) due to the following issue: 

http://puu.sh/miZiR/4c4fe5d410.png

**Comment by natew** [comment]
Ah, this is actually a bigger thing than I expected. Working on fix.

**Comment by natew** [comment]
Ok this was quite the path to go down, we were missing a big piece of functionality. I actually am not sure it's fully working. I tested with the site and I can see babel-runtime now coming through properly.

This probably requires quite a few fixes still! But I pushed out a release that starts this fix.

https://github.com/flintjs/flint/commit/61c2898c25ca708fdf8a44390c3cb7368559f432
