### ISSUE TITLE
Errors in flint.dev.js

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#220]
We should basically just replace any internal error with "error in flint internals" or something similar. flint.dev.js shows fairly often, looks bad, and doesn't help the user

**Comment by natew** [comment]
d74291d

**Comment by ncammarata** [comment]
awesome!

**Comment by natew** [comment]
It's not perfect we could show better info on what happened. And notify would be good we should be careful of tracking should be opt in somehow
