### ISSUE TITLE
flint (and flint build) hangs forever after installing packages

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#221]
Here's the entire output of `flint --debug` which I ran after `rm .flint/.internal` with `flint --version` = `1.4.0-beta.20`: https://gist.github.com/liron00/466dcb79faed596ea0e0

**Comment by liron00** [comment]
For comparison, here's what `flint --version` = `1.3.136` looks like when everything works fine: https://gist.github.com/liron00/f288f415c04e477414aa

**Comment by natew** [comment]
Should be fixed up
