### ISSUE TITLE
Auto-output -webkit-flex-direction

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#258]
When I add a flexDirection style, it doesn't work on iOS 8 Safari because there's no -webkit-flex-direction getting outputted.

**Comment by natew** [comment]
Will check this could be a regression or bug in one of our output libraries.

**Comment by natew** [comment]
Is it dynamic? On css its prefixed, I realized I disabled radium prefixing am releasing new build with it re-enabled. I don't see it in safari though but maybe its being really smart and only prefixes when on an old safari.

**Comment by natew** [comment]
Try out `>= v1.4.43`
