### ISSUE TITLE
Flint Atom Plugin

### ISSUE THREAD

**Issue by natew** [flintjs/flint#26]
Let's start with Atom and move to Sublime quickly, then vim. It should do at base:

- [x] Drag numbers
- [x] Live Color Picker
- [ ] Custom syntax highlight (detect views/styles better)
- [x] Save as you type option
- [ ] Suggestions for CSS attributes (autocomplete eventually)
- [ ] Tag create syntax (type word and hit key to complete tag either self-closing or regular)
- [ ] Collapse/expand all styles
- [ ] Collapse/expand all views
- [ ] Go to view in project

**Comment by natew** [comment]
https://github.com/flintjs/flint-atom @ncammarata I can't get apm to publish this for me after at least 10 different attempts... could you try?

**Comment by natew** [comment]
@ncammarata :smile:

**Comment by ncammarata** [comment]
https://atom.io/packages/flint

**Comment by ncammarata** [comment]
@natew can you delete https://atom.io/packages/atom-flint I think you're the owner

**Comment by natew** [comment]
Whitespace being chopped by dragger: https://v.usetapes.com/a5l22Ex1rL

**Comment by natew** [comment]
Bug: https://v.usetapes.com/Hxm14fiixB

**Comment by natew** [comment]
- [ ] Hold super (or some) key to enable all the super mode stuff, rather than having dragging/colors as separate key shortcuts
- [ ] Highlight DOM node when you have super key on
- [ ] Highlight styles of element you are currently in, and vice versa
