### ISSUE TITLE
on.keydown still detects events after the view is unmounted

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#260]
on.keydown(e => {
        if (!view.mounted) {
            console.log('FAIL')
        }
    })

Have the parent mount and unmount this view, and then press a key.

**Comment by natew** [comment]
I did notice this in our demos, definitely a new bug. High priority.

**Comment by natew** [comment]
Quite a few bugs I found in there unfortunately, not sure where they all came from.

Should be way way better overall. Fixed all sorts. Let me know.
