### ISSUE TITLE
Flint doesn't recover from Invariant Violation error

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#264]
I'm on flint v1.4.38 and Atom 1.4.0

Here's some simple code

```javascript
const formulas = [
  {
    name: 'Area of a square',
    formula: 'A = bh'
  }, {
    name: 'Area of a square',
    formula: 'A = bh'
  }
];

view Main {
  <h1>Formulas</h1>
  <main>
    <div repeat={formulas}>{_.name}</div>
  </main>

  $h1 = {
    color: 'cadetblue',
    padding: 20
  }
}
```

While typing out `{_.name}` because flint reloads too fast it throws this error:

`Uncaught Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {name, formula}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.`

Any changes I make to the flint file afterwards do not result in a live reload. However, if I just refresh the page I get the live reloading back.

**Comment by natew** [comment]
Oh yea, ok. I had a fix for this at one point that automatically stringified objects, for this very reason. But we took it out because it was causing a few other issues.

I think we can fix this by detecting an object that would trigger this error, and just showing a Flint error and leaving it blank in render.

**Comment by AriaFallah** [comment]
:+1:

**Comment by natew** [comment]
Ok, we now have a beautiful new error message for this:

![image](https://cloud.githubusercontent.com/assets/12100/12501050/cf5c8dd6-c06d-11e5-9bc8-6967c62be832.png)

**Comment by AriaFallah** [comment]
@natew perfect thanks!
