### ISSUE TITLE
Flint CLI always says there is an update available.

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#267]
Might be because `flint --version` always is 1 less than the actual version you installed.

**Comment by natew** [comment]
@AriaFallah wondering if this is a npm cdn delay. Do you still get it a few hours later? (assuming you update to latest first)

**Comment by AriaFallah** [comment]
Just updated to latest, and still the same thing. I do have version 1.4.41 even though it says 1.4.40.

**Comment by natew** [comment]
One thing we could consider is just not warning for patch releases anyway

**Comment by marcus** [comment]
Same problem here - I actually do have the current version installed, it just warns ever time as if it wasn't installed. I do like the warning for patch releases though.

**Comment by natew** [comment]
New version uses `semver-compare` to make checks and should fix a couple things. Is this fixed?

**Comment by AriaFallah** [comment]
<img width="243" alt="screen shot 2016-01-24 at 7 34 56 pm" src="https://cloud.githubusercontent.com/assets/9424976/12540152/9859bdca-c2d1-11e5-8d03-0962d3f1d1fe.png">
@natew nope :cry:

**Comment by natew** [comment]
Ok in 1.4.65 a new attempt at a fix.

**Comment by AriaFallah** [comment]
@natew installing now

**Comment by AriaFallah** [comment]
@natew "Update available" message is gone!
