### ISSUE TITLE
Flint reloads so quickly it'll install random packages when typing an import statement.

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#270]
Or even if I make a typo. Oftentimes I have to restart the flint CLI because the automatic uninstalling fails.

Possible solutions:

* Debouncing the reload.
* Not installing packages unless you save.

**Comment by natew** [comment]
It should debounce the install by about 500ms (could be more), and the auto-uninstalls after 3 seconds so any bad packages remove.  We should have notification for uninstall.

What happens that makes you restart?

Thought it could hang. For demos its been helpful to have it less debounced.

**Comment by AriaFallah** [comment]
@natew yeah sometimes I get butter fingers and screw up the package name with prob more than 500ms delay.

I have to restart because it gets stuck on `uninstall <packagename>` sometimes and won't reload. However it does successfully remove the package.
