### ISSUE TITLE
remove special dash tags <name-tag>

### ISSUE THREAD

**Issue by natew** [flintjs/flint#272]
Now that we have tagName prop, this should go away, esp since its already valid html to do dash tags for custom element.

@liron00

**Comment by AriaFallah** [comment]
@natew does include providing any way to style tags with dashes?

**Comment by natew** [comment]
@AriaFallah that should be a conversation, opening ticket...

**Comment by natew** [comment]
Removed in 1.4.56

**Comment by liron00** [comment]
What if I want to have a <Link> which just renders an <a> with no view
wrapper?


On Saturday, January 23, 2016, Nate Wienert <notifications@github.com>
wrote:

> Removed in 1.4.56
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flintjs/flint/issues/272#issuecomment-174245423>.
>


-- 
--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by natew** [comment]
view Link { <a root yield /> }

**Comment by liron00** [comment]
Where's the <a> part?

On Saturday, January 23, 2016, Nate Wienert <notifications@github.com>
wrote:

> view Link { }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flintjs/flint/issues/272#issuecomment-174245486>.
>


-- 
--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by natew** [comment]
`view Link { <a root yield /> }`

**Comment by liron00** [comment]
Lol ok and what's yield?

On Saturday, January 23, 2016, Nate Wienert <notifications@github.com>
wrote:

> view Link { <a root yield /> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flintjs/flint/issues/272#issuecomment-174245560>.
>


-- 
--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by AriaFallah** [comment]
@liron00 I think it passes all props down.
