### ISSUE TITLE
State Inspector: don't move input position on type

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#277]
https://v.usetapes.com/ES31rJtyr8

I pressed backspace on "i" and it refreshed my spot. Not sure how to do this in general

**Comment by AriaFallah** [comment]
https://github.com/dockyard/ember-one-way-controls

Relevant part:

<img width="939" alt="screen shot 2016-01-23 at 9 21 57 am" src="https://cloud.githubusercontent.com/assets/9424976/12530640/cf750258-c1b2-11e5-8206-3df9c6c75e66.png">

**Comment by natew** [comment]
fixed in 4d33e080af59f61be77963df705387108ce0bd45
