### ISSUE TITLE
Allow config option to build to a certain directory.

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#281]
Low priority thing, but it's a little annoying. After running `flint build`, I pretty much never need the build inside of the `.flint` directory.

It would be convenient to be able to specify a location to build to.

Something like

    flint build --location=../parse/public

**Comment by natew** [comment]
For now `flint build && mv .flint/build ../otherplace` but yea eventually

**Comment by AriaFallah** [comment]
I thought about this a bit more, and I think it'd actually be pretty silly to have it as a command line arg since as you pointed out `mv` exists.

However, it could be valuable as a config option in your flint.json like

```javascript
{
  "build_directory": "../dist" // relative to your project path not .flint/build
}
```

Low priority thing again, but at least this makes my request a bit more useful.

**Comment by natew** [comment]
`--out` now supports this, it's alpha so be careful using it. Feel free to report bugs. You should be able to set the out option in your config as well to have a default.
