### ISSUE TITLE
Generator functions crash flint

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#287]
I think this is definitely related to #285 because it has to do with the babel-runtime polyfill not working properly.

    var _regeneratorRuntime = require('babel-runtime/regenerator').default

^ Line with issues. `cannot read default of undefined`

**Comment by natew** [comment]
Fix coming in a few minutes for these.

**Comment by natew** [comment]
This should be fixed in new version, but I'm getting error until I refresh. Try it out.
