### ISSUE TITLE
Guarantee build modules

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#288]
My built modules are often not available after building a Flint apps.

This leads to confusing errors like
```js
Uncaught ReferenceError: ___keycode is not defined
```

Idea: require the expected modules internally to gaurantee that they work. If they don't work, we can show a nicer error and try rebuilding them. Would be a UX improvement long term(checking packages for them) and a huge bandaid short term (while also fixing the underlying bugs) @natew

**Comment by natew** [comment]
I'm going to be bold and close this as there was a big bug in this earlier and I've spend a few days attacking this. Lets see if it crops up again and re-open.
