### ISSUE TITLE
Split `transform` into separate process

### ISSUE THREAD

**Issue by natew** [flintjs/flint#293]
I think we could get away with this and it would be a worthwhile speedup.

**Comment by ncammarata** [comment]
why would this be faster perf wise? Or do you mean just development wise it's better to not have one big file

**Comment by natew** [comment]
Well it would use multiple cores if separate what I didn't think about is synchronicity. Left this here so I could think about it later. I'm thinking cached start gets more benefits than this with easier impl. We could split any number of things into processes though.
