### ISSUE TITLE
Really malformed error reported by flint

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#295]
I was missing a `.` in the code below

```javascript
normalize(query.includes(TEST_CLASS)find())
```

and I got this

![screen shot 2016-01-26 at 10 58 42 am](https://cloud.githubusercontent.com/assets/9424976/12585854/d7331adc-c41b-11e5-9d98-1d417e5ff430.png)

**Comment by natew** [comment]
This should be fixed!
