### ISSUE TITLE
Need to refresh browser twice to get changes to code outside views to be acknowledged in the browser.

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#296]
I think this started happening during the update after you fixed the polyfills not being loaded properly.

I was editing this file, which is outside a view just in case you need it.

https://github.com/AriaFallah/formulagrid/blob/master/src/reducers/index.js

**Comment by natew** [comment]
Committed a few things this morning (1.4.84) that aim at this, let me know if its better.

**Comment by AriaFallah** [comment]
Not happening for the time being. Will reopen if I see it again.
