### ISSUE TITLE
Changing the name of your flint directory ruins the real time hot reloading.

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#297]
To reproduce make a flint app

```bash
flint new test
cd test
flint
```

And then rename the folder

```bash
mv test a
```

For me this breaks the super fast hotreloading. In my case I changed it from `formulagrid` to `src`, which screwed everything up.

This might also be why #296 was occurring.

**Comment by AriaFallah** [comment]
Changing the directory name back also doesn't seem to reenable it...gonna see if I can somehow get it operational again.

**Comment by AriaFallah** [comment]
Ok so after some more testing even completely new flint apps don't hot reload so I'm not sure what I broke, but it was a lot of things.

@natew or @ncammarata could one of you verify the directory name changing is actually a thing?

**Comment by montogeek** [comment]
I think that is ok HotReloading stops working if you rename a folder

**Comment by natew** [comment]
As long as it starts working again when you run the server again, is that the case?

**Comment by montogeek** [comment]
Yes, for me, it is an expected behaviour
