### ISSUE TITLE
Real time hot reloading being very inconsistent.

### ISSUE THREAD

**Issue by AriaFallah** [flintjs/flint#298]
I closed #297 because I think it's just me. Even with a completely fresh project I don't have the real time reloading.

I made a video just so it's more clear:

https://streamable.com/h6u1

It still reloads every time I save the file as you can see in the video, but nothing happens as I type.

`flint --reset` also doesn't work. This was after running `npm uninstall -g flint` and then `npm install -g flint` to make sure I had a fresh version.

**Edit: I tried it a few more times and sometimes it worked and sometimes it didn't** :confused:

**Comment by ncammarata** [comment]
this isn't a very specific issue, so I'll close it, but live coding really does require a deep dive sometime in the next couple days

**Comment by natew** [comment]
1.5 has a variety of build system things, and hot reloads are working pretty well for me in it. Comment here if things are still broken!
