### ISSUE TITLE
Deep NPM errors

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#3]
I'm using YQL which requires 'fs'. We should throw an error saying "YQL is trying to access FS" or something similar. 

![image](https://cloud.githubusercontent.com/assets/204989/10474619/9612ebf2-71ed-11e5-9a69-75bf491bbe5e.png)

Right now we throw this and it's not super helpful.

**Comment by natew** [comment]
It should install fs if necessary. Can I have a test case?

**Comment by ncammarata** [comment]
It's less a test case and more for the common use-case of accidentally using a server-side module for client-side, because a lot of modules don't explicitly document that since client side is newer. Ran into this several times while building out an app and trying different modules. A better type of error would say "cannot install YQL because it accesses "fs" which doesnt exist" or something similar

**Comment by natew** [comment]
https://github.com/flintjs/flint/commit/b64b5347b3c57aa4b7f28d6c987cd376ed0e3823
