### ISSUE TITLE
hover is broken

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#308]
```js
view Main {
  <h1>Hello world!</h1>

  $h1 = {
    fontSize: 30,
    hover: { fontSize: 60, }
  }
}
```

this may be just my branch, but 90% sure it's master

**Comment by AriaFallah** [comment]
Hey I think this is possibly just a typo on your part:

For me it works with `':hover':` instead of `hover:`

```javascript
view Main {
  <h1>Hello to the world!</h1>

  $h1 = {
    color: 'limegreen',
    padding: 20,
    ':hover': {
      fontSize: 60
    }
  }
}
```

**Comment by natew** [comment]
This is working fine for me. @AriaFallah actually we support hover as well.

**Comment by AriaFallah** [comment]
@natew Oh I had no idea :open_mouth:

**Comment by ncammarata** [comment]
sorry - was actually my issue
