### ISSUE TITLE
Remove span from elements with dynamic content

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#31]
```js
view Main {
  let what = 'welcome'
  let where = 'flint'
  
  <thing>{what} to {where}!</thing>

  $ = {
    alignItems: 'center',
    justifyContent: 'center'
  }
}
```
renders
![image](https://cloud.githubusercontent.com/assets/204989/10656764/2ec6a984-7837-11e5-848d-ba7031b8377e.png)

with html

![image](https://cloud.githubusercontent.com/assets/204989/10656772/3d672edc-7837-11e5-942f-17502ea638a9.png)

**Comment by natew** [comment]
Probably not solvable until: https://github.com/facebook/react/issues/1236

**Comment by natew** [comment]
Closing because it's not under our control
