### ISSUE TITLE
Deep folder errors

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#33]
I'm structuring my app like

```
/pages/page1/main.js
/pages/page2/main.js
```
and when I have an error I don't know which folder it's in

![image](https://cloud.githubusercontent.com/assets/204989/10658178/474201ae-7849-11e5-9d21-fb27d1e4c429.png)

It would be more helpful to see page1/main.js as a label

**Comment by natew** [comment]
Fixed in 00c9f11
