### ISSUE TITLE
Make comments easier

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#34]
I had a piece of code

```js
<State if={['/','state'].indexOf(Flint.router.location) > -1} />
```

and wanted to change it to

```js
<State /> // if={['/','state'].indexOf(Flint.router.location) > -1} />
```

or something similar, and there were no good ways of doing that. There should be

**Comment by natew** [comment]
I think a regex is actually fairly safe here, no? We could modify the jsx parser in Babel, but is there ever a case where (//) doesn't hide the rest of the line (while in jsx?)

**Comment by ncammarata** [comment]
<a href="http://google.com">

we could consider a comment "anytime // is listed with a space before and after" but it runs into the issue where some people link to <a href="//foobar.com"> and omit the http:. Regex wouldn't capture inside the strings

**Comment by natew** [comment]
Any prop or HTML that has `//` would break this...

```js
<div>
  We are cool // fun
</div>

<App gets="this // breaks" />
```

**Comment by ncammarata** [comment]
yeah, the point I was making above is basically that the cool // fun is super rare. But double //s in links are common, and a case we need to take into consideration

**Comment by natew** [comment]
Close for now, this one probably won't ever bubble up high enough. Unless you want to open discussion with the React folks on a JSX  / Babel thread.
