### ISSUE TITLE
Save/Success/Error indicator in development

### ISSUE THREAD

**Issue by natew** [flintjs/flint#47]
Show in favicon as a green/yellow/red for success/saving/error. To give users confidence their save actually propogated.

**Comment by natew** [comment]
Also status for "Disconnected", so you remember if you killed your server.

**Comment by ncammarata** [comment]
![image](https://cloud.githubusercontent.com/assets/204989/12699947/3b903e4a-c784-11e5-82f2-dbef8b92342d.png)

could we take over this?

**Comment by steelbrain** [comment]
@ncammarata I don't think that's a good idea. We could however show a colored indicator in the bottom bar
