### ISSUE TITLE
Better errors for dashes in style properties

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#55]
![image](https://cloud.githubusercontent.com/assets/204989/10749126/16c2e55a-7c24-11e5-9ec9-ea343bead2cb.png)

**Comment by natew** [comment]
Thats seems alright, I do think we could add subscripts to error messages to show full stacks and extra info. We could say underneath (Did you mean to write...?)

![screen shot 2015-10-27 at 4 14 20 am](https://cloud.githubusercontent.com/assets/12100/10756417/38a90216-7c61-11e5-963c-2d03ad532b70.png)

**Comment by natew** [comment]
Dup of https://github.com/flintjs/flint/issues/23
