### ISSUE TITLE
Make <foo-MyView> work like <foo-tag>

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#66]
Let `<foo-MyView>` and `<bar-MyView>` be styled by `$foo` and `$bar`.

**Comment by natew** [comment]
Leaving this one open for discussion.

My thoughts are classes are more appropriate, and this could be confusing. This change would be consistent with the tag stuff in HTML, but to be honest I'd rather remove the <name-tag> option with something better than go all in on the `-`. But open to discussion!

**Comment by natew** [comment]
Closing for now, we want to eventually just drop the `-` syntax, but classes do work now:

`<MyView class="blue />` will pick up $blue styles.
