### ISSUE TITLE
Flint.router.go reactivity bug

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#69]
`<UserPage route="/:userSlug" />`

If I do `Flint.router.go("/liron")` in the console, it properly displays the UserPage.

But if I do `Flint.router.go("liron")`, it doesn't display the UserPage, even though the absolute URL still becomes `/liron`.

**Comment by natew** [comment]
Pushed a patch that lets you do `Flint.router.go("liron")` and shows a sub page with the route `/liron`.
