### ISSUE TITLE
Object.assign call isn't recognized as a mutator

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#70]
![image](https://cloud.githubusercontent.com/assets/699733/10802962/ea677c8c-7d7c-11e5-8b05-c42c8eb97544.png)

The view.update() call shouldn't be necessary.

**Comment by natew** [comment]
I put in a fix for this one the other day actually. Will check it out.

**Comment by natew** [comment]
![screen shot 2015-10-28 at 4 23 11 pm](https://cloud.githubusercontent.com/assets/12100/10806135/34a74850-7d90-11e5-9f3b-950fc92d3d62.png)

**Comment by natew** [comment]
Looks good to me with latest version
