### ISSUE TITLE
forms should preventDefault by default

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#72]

**Comment by natew** [comment]
Can I get some justification?

**Comment by ncammarata** [comment]
users keep running into it and no one wants an empty form to refresh the page

**Comment by natew** [comment]
Mostly I don't know what you mean by prevent default. Like an example and what happens

**Comment by ncammarata** [comment]
```js
view Main {
  <h1>hello</h1>
  <form>
    <button>hi</button>
  </form>
}
```

refreshes the page

```js
view Main {
  <h1>hello</h1>
  <form onSubmit={e => e.preventDefault()}>
    <button>hi</button>
  </form>
}
```

this would be better by default I think

**Comment by natew** [comment]
We should be pretty conservative on changing behavior. Oftentimes forms are external. We could explore some sort of helper, but changing default here could confuse.
