### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by natew** [flintjs/flint#73]
Lets log some improvements we could do here. Saw someone write this today:

```
view Main {
  async function() { async fetch() }
}
```

Which returns a really obtuse error!

**Comment by natew** [comment]
http://d.pr/i/aNkM

**Comment by ncammarata** [comment]
npm module 404 could be cleaner (not eat up 90% of small pages)

https://cloudup.com/clET_JipMO3

**Comment by natew** [comment]
This is after I've cleaned it up a bunch. We'd need to architect it a bit to handle various npm messages if we want better.
