### ISSUE TITLE
Don't mess with "^" character in regex literals

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#75]
let regex = /[^x]/
    console.log(regex.toString())

Expected: `/[^x]/`
Got: `/[view.props.x]/`

**Comment by liron00** [comment]
And in strings...

    let s = "b^c"
    console.log(s)

Expected: `b^c`
Got: `bview.propsc`

**Comment by natew** [comment]
Yea, we've been talking about removing it. It's the last piece of jank in the system. Still wish we had a better way to do props than `view.props` though.

**Comment by natew** [comment]
Fixed in `runner@v1.3.36`
