### ISSUE TITLE
Local imports

### ISSUE THREAD

**Issue by natew** [flintjs/flint#78]
We've discussed this and come up with a strategy. As of today Flint doesn't let you do:

```js
import x from './lib/x'
```

This is a gap in feature. We left it out as long as possible to see how it felt building an app with just global constants from `main.js` and using stuff from npm. Of course, that isn't viable in bigger apps.

Why did we leave it out? Well, part of the speed of our hot reloads are due to the fact we don't build out a bundle! Import/export systems end up having circular dependencies, this requires you to build one big monolithic bundle every time you save. So we avoided them.

How can we have our cake and eat it too? I think we've figured out something that works well. In practice, most of your files would never `export` anything, because views don't need to be imported or exported.

So, we read files that have an `export`. If they do, we bundle them with webpack. If they don't, we leave them as they are now (unbundled, and joyously fast).

We inject the bundle before the scripts, and when it changes, call `Flint.render`. We can export the bundled files into some namespace, maybe `__flintLocals`. And let them be required.

I believe this has no downsides besides the fact we have to implement it!

Oh, and I could see views being in the bundle going slower, we should probably actually disallow it altogether to avoid complexity, which would be pretty easy. Plus, you almost always want some sort of `lib` folder with all your functions, and just stuff in there would export.

**Comment by ncammarata** [comment]
until we have this, we suggest just adding things globally, it'll be super easy to migrate when we support local exports. For now

in lib/square.js
```
  let square = x => x * x
  /* lots of code here doing complicated stuff */


  window.Square = sq
```

Then you can just use Square where you want. When we add local imports:

```
  let square = x => x * x
  /* lots of code here doing complicated stuff */

  export default square
```

**Comment by natew** [comment]
Support for this integrated today, but hot reloads with it are still a little sketchy. We can open separate issues for bugs from here on.

**Comment by ncammarata** [comment]
this is awesome

**Comment by liron00** [comment]
(Nick on Liron's Computer) There are issues if I try to export from main, which is something we actively supported before, and might want to try to throw a better error for
