### ISSUE TITLE
view Dialog should create a div not <dialog>

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#85]

**Comment by natew** [comment]
Does it cause weird rendering issues?

I'm a little torn on this because we should allow people to use all html elements, but it is a weird situation blacklisting some of them.

**Comment by ncammarata** [comment]
yeah in an example I was building it wasn't rendering for me. https://github.com/flintjs/examples/blob/master/modal/main.js change Modal to Dialog to try

**Comment by natew** [comment]
Should be fixed in flint-js@1.3.63
