### ISSUE TITLE
Test test test

### ISSUE THREAD

**Issue by natew** [flintjs/flint#87]
Let's sign up here: https://travis-ci.org/

And use [this wonderful library](https://github.com/tmpvar/jsdom) @tmpvar :wave: 

To test our compiled output: DOM structure + styles

And then mimic [this setup](https://github.com/rackt/react-router/blob/master/modules/__tests__/History-test.js) to test our internal stuff

**Comment by tmpvar** [comment]
:wave:

**Comment by natew** [comment]
Radium has a nice setup as well.
