### ISSUE TITLE
Semicolon insertion based on html indentation

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#89]
![image](https://cloud.githubusercontent.com/assets/204989/10896172/106c01e8-816d-11e5-8a2c-bbf1f0ba45a3.png)

creates

![image](https://cloud.githubusercontent.com/assets/204989/10896168/0c688260-816d-11e5-9b96-409f666d692f.png)

with an indented h2 there's no semicolon insertion
![image](https://cloud.githubusercontent.com/assets/204989/10896181/18a33048-816d-11e5-9f2c-8ac78d470d8d.png)

**Comment by natew** [comment]
Needs Babel to asi for us. Can look into difficulty.

**Comment by natew** [comment]
Looks like we have a fix in, will be testing upgrade to babel 6 today: https://github.com/babel/babel/issues/2591#issuecomment-153324810

**Comment by natew** [comment]
Goes with our 6 ticket!
