### ISSUE TITLE
Routing other URLs doesn't work on deployed site

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#91]
https://flashcash.money

Flint.router.go() works as expected, but when an external source links the user to a URL like https://flashcash.money/faq, the Flint app doesn't trigger so the router can't kick in.

Arguably this is my own problem to solve, not Flint's, but anyone who tries to get up and running with Firebase will want to know the answer so it's probably worth addressing in the docs.

**Comment by ncammarata** [comment]
![image](https://cloud.githubusercontent.com/assets/204989/10925934/58be72ac-8247-11e5-9a20-88988b7cbc4f.png)

https://www.firebase.com/docs/hosting/guide/full-config.html#section-advanced-properties

It will now always render your base index.html file

**Comment by liron00** [comment]
Fixed thanks.
